# Generated by Django 3.1.2 on 2020-12-01 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='year_of_relevance',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='photo_url',
            field=models.URLField(default='https://lh3.googleusercontent.com/proxy/TVM3xpx4lmNgijx4Lq5x0zTAA7hC_eVNU-BlThVBvmnxdKBO8MXFOPnU5QjQIsOj22SGH2AmVAbEBkFuOSWEl13wbw', max_length=256),
        ),
        migrations.AlterField(
            model_name='materials',
            name='link',
            field=models.URLField(max_length=256, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
