# Generated by Django 3.1.2 on 2020-10-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.IntegerField(null=True),
        ),
    ]
