# Generated by Django 3.1.1 on 2020-10-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='apmath_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='photo_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='vk_discuss_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('abstract', 'конспект'), ('questions', 'вопросы'), ('test', 'контрльная')], max_length=16)),
                ('link', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lecturer')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.programme'),
        ),
    ]
