# Generated by Django 3.1.2 on 2020-10-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subject_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.subject'),
        ),
    ]
