# Generated by Django 3.1.5 on 2021-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201201_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='only_authorized_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='photo_url',
            field=models.URLField(default='https://sun9-68.userapi.com/impf/HyenmwTQQ1fWW0OszQm_mih7lYpbLZ0NxveoJQ/NEYM96WpZVw.jpg?size=512x512&quality=96&proxy=1&sign=62af85c2f2a71ab9252ea738532a87be', max_length=256),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='vk_discuss_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='year_of_relevance',
            field=models.IntegerField(default=2021),
        ),
    ]
