# Generated by Django 3.1.1 on 2020-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201014_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='apmath_url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='photo_url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='vk_discuss_url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='materials',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='materials',
            name='lecturer',
            field=models.ManyToManyField(null=True, to='main.Lecturer'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='link',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='img_url',
            field=models.URLField(max_length=256),
        ),
    ]
