# Generated by Django 3.1.1 on 2020-10-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201014_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='subject',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='subject',
            field=models.ManyToManyField(null=True, to='main.Subject'),
        ),
        migrations.RemoveField(
            model_name='materials',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='materials',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lecturer'),
        ),
    ]
