# Generated by Django 3.1.2 on 2020-10-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201014_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='main.subject'),
        ),
    ]
