# Generated by Django 3.1.2 on 2020-10-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201014_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='subject',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='subject',
            field=models.ManyToManyField(to='main.Subject'),
        ),
    ]
