# Generated by Django 3.1.2 on 2020-10-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201014_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'subject': models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lecturer'),
        ),
    ]
