# Generated by Django 3.1.2 on 2020-10-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201014_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='term',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='subject',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject'),
        ),
    ]
