# Generated by Django 3.1.2 on 2020-10-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lecturer_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='programme',
        ),
        migrations.AddField(
            model_name='programme',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура')], max_length=16),
        ),
    ]
