# Generated by Django 3.1.2 on 2020-10-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201015_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура')], max_length=16),
        ),
    ]
