# Generated by Django 3.1.1 on 2020-10-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201015_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
