# Generated by Django 3.1.2 on 2020-11-23 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20201015_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materials',
            name='type',
            field=models.CharField(choices=[('abstract', 'конспект'), ('questions', 'вопросы'), ('test', 'контрльная'), ('other', 'разное')], max_length=16),
        ),
    ]
